meta_product_name: "Trust-in"
meta_title: "Trust-in - Bénéficiez des services recommandés par votre réseau"
meta_description: "Trouvez des services et bons plans recommandés par votre réseau de proximité : babysitting, cours de soutien, petsitting ou autres services et bons plans"
meta_image: "boulognehome.png"                       # should exist in `app/assets/images/`
twitter_account: "@Trust-in_twitter_account"   # required for Twitter Cards
