meta_product_name: "Trust-in"
meta_title: "Trust-in - Partage de bons plans et services avec votre réseau"
meta_description: "Trouvez des services et bons plans recommandés par votre réseau de proximité pour vous aider votre quotidien. Partagez avec votre réseau des recommandations sur des prestataires de confiance : babysitting, cours de soutien, petsitting ou autres bons plans pour se simplifier le quotidien"
meta_image: "boulognehome.png"                       # should exist in `app/assets/images/`
twitter_account: "@Trust-in_twitter_account"   # required for Twitter Cards
